### ISSUE TITLE
Docker Not working

### ISSUE THREAD

**Issue by dawsonjkraai** [Selbi182/SpotifyBigPicture#39]
Hello. So I am trying to set this up on docker. I followed your instructions but I keep getting the following from the docker logs.

`        ... 26 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [spotify.api.SpotifyApiManager]: Constructor threw exception; nested exception is java.lang.IllegalStateException: 'redirect_uri' must end with /login-callback
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:226) ~[spring-beans-5.3.31.jar!/:5.3.31]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.3.31.jar!/:5.3.31]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:306) ~[spring-beans-5.3.31.jar!/:5.3.31]
        ... 49 common frames omitted
Caused by: java.lang.IllegalStateException: 'redirect_uri' must end with /login-callback
        at spotify.api.SpotifyApiManager.generateRedirectUri(SpotifyApiManager.java:218) ~[spotify-dependencies-1.11.2.jar!/:na]
        at spotify.api.SpotifyApiManager.<init>(SpotifyApiManager.java:67) ~[spotify-dependencies-1.11.2.jar!/:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:na]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:213) ~[spring-beans-5.3.31.jar!/:5.3.31]
        ... 51 common frames omitted`

I did get it working via windows using the jar file and batch file. No problem. I did change my redirect URL from localhost to the IP of the docker container. I gave the docker host. I did also try giving the container its own IP to see if that would help but no luck. This is what I have the call back URL set to: "http://192.168.1.22:8183/login-callback" (192.168.1.22 being the container's IP)

Let me know what I should try or if you need more info. Great project by the way!

**Comment by Selbi182** [comment]
Hmm, I'm not really sure... It looks like you've set up the _redirect_uri_ incorrectly, but _/login-callback_ is correct.

What's your docker run prompt? You should be able to set a specific redirect URI using the -e parameter.
