### ISSUE TITLE
UnsupportedClassVersionError

### ISSUE THREAD

**Issue by GreenRabbits** [Selbi182/SpotifyBigPicture#5]
Hi,
Before anything else, thank you for creating this project that may be useful since Spotify has removed the Album Art fullscreen feature a few years ago.
However, I am stuck and can't run the file SpotifyBigPicture.jar with a terminal. I've just installed Java and it tells me that the version is have is outdated. I get this error :

Exception in thread "main" java.lang.UnsupportedClassVersionError: spotify/SpotifyBigPicture has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)

Do you know how to solve this error ?

**Comment by Selbi182** [comment]
Hey there, thank you for your interest!

The error most likely means that your Java version is too old. I'm assuming you're still running on Java 8, but this project requires at least Java 11. Make sure you update and then try again! :)

**Comment by GreenRabbits** [comment]
That worked, thank you !
Now, I see a blank screen with the date only. When I open the browser console, I get a "Flux onerror" :  

error { target: EventSource, isTrusted: true, srcElement: EventSource, currentTarget: EventSource, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … 
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: null
defaultPrevented: false
eventPhase: 0
explicitOriginalTarget: EventSource { url: "http://localhost:8183/playback-info-flux", withCredentials: false, readyState: 2, … }
isTrusted: true
originalTarget: EventSource { url: "http://localhost:8183/playback-info-flux", withCredentials: false, readyState: 2, … }
returnValue: true
srcElement: EventSource { url: "http://localhost:8183/playback-info-flux", withCredentials: false, readyState: 2, … }
target: EventSource { url: "http://localhost:8183/playback-info-flux", withCredentials: false, readyState: 2, … }
timeStamp: 88018
type: "error"
<get isTrusted()>: function isTrusted()
<prototype>: EventPrototype { composedPath: composedPath(), stopPropagation: stopPropagation(), stopImmediatePropagation: stopImmediatePropagation(), … }

The jar program seems to run correctly, I've got "SpotifyBigPicture is ready!" and a bunch of new lines appear periodically when it is running.

**Comment by Selbi182** [comment]
These errors are unavoidable unfortunately, but as long as you have music playing on Spotify, it should work

**Comment by SounakSinha** [comment]
I have the exact same issue. I can see only the clock on a grainy background. Didn't work on Firefox and Edge.

Can you detail how to use it exactly? Is it supposed to read the data from any device I'm playing Spotify from?

**Comment by Selbi182** [comment]
Hmm, that's a really strange. The interface should work anywhere, all it does is display what music you're playing on Spotify. It doesn't matter where the playback is. It could be the same PC where you host the interface from, or across the globe on your phone.

If that's okay with you, could you add me on Discord: Selbi#7270

I'm not sure how to approach this problem without further information. Maybe it's an issue on your end, maybe it is one on the app's side.

**Comment by Selbi182** [comment]
Good news! I was able to fix a couple of issues related to the login process. Please try again with the new release and tell me if it worked for you: https://github.com/Selbi182/SpotifyBigPicture/releases/tag/v0.3

Make sure to replace the application.properties file, as I forgot an important setting there required for the login.

**Comment by GreenRabbits** [comment]
Thank you ! v0.3 works perfectly !

**Comment by Selbi182** [comment]
I'm glad it worked! If you need any further assistance, don't hesitate to let me know 😊
